# Generated by Django 5.1.1 on 2025-01-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_conversation_history_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='history',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
